#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 6.0.{build}.0
image: Visual Studio 2017
install:
    - git clone https://github.com/johlju/DscResource.Tests
    - ps: Push-Location
    - ps: cd "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests"
    - git checkout ordered-tests
    - ps: Pop-Location
    - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Write-Verbose -Message 'Removing all SQL related PowerShell modules so they can not be used by the common tests.' -Verbose
        Write-Verbose -Message 'This is a workaround because the AppVeyor build worker image contains SQL Server. More information in issue #239.' -Verbose
        Write-Verbose -Message 'Modules that are being removed:' -Verbose
        Get-Module -ListAvailable -Name 'sql*' | ForEach-Object -Process { Write-Verbose $_.Path -Verbose; Remove-Item $_.Path -Force -Verbose; }

        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo -ExcludeTag @()

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask
